name: C/C++ CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        mpi: [ 'mpich', 'openmpi' ]

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup MPI
      uses: mpi4py/setup-mpi@v1
    - name: make dev
      run: make dev
    - name: make run
      run: make run
