name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    strategy:
      matrix:
        #mpi: [ 'mpich', 'openmpi' ]
        os: [ubuntu-latest, macOS-latest, macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: pip install -e
    - name: Run examples
      run: |
      ./examples/lennardjones/basic.py
      ./examples/lennardjones/objects_only.py
      ./examples/vashishta/basic.py
      ./examples/vashishta/objects_only.py
      ./examples/vashishta/uvt.py
