name: tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
    - cron: '0 2 * * *' # run at 2 AM UTC

jobs:
  build:
    strategy:
      matrix:
        os: [ubuntu-latest, macOS-latest, macOS-11]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8
    - name: Install dependencies
      run: python -m pip install .
    - name: Run examples
      run: |
        python examples/lennardjones/basic.py
        python examples/lennardjones/objects_only.py
        python examples/vashishta/basic.py
        python examples/vashishta/objects_only.py
        python examples/vashishta/uvt.py

